---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/flux/olm
  prune: false
  sourceRef:
    kind: GitRepository
    name: catalog
